/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package application;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import fileManager.FileManager;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext(
            SpringConfig.class
        );

        FileManager fileManager = context.getBean("fileManager", FileManager.class);
        context.close();
    }
}
